"""Utility functions for the warehouse inventory system."""

__all__ = [
    "format_sku",
    "load_csv",
]

import csv
from pathlib import Path

from warehouse.models import Product

#: Default prefix applied to all SKUs generated by this warehouse system.
#: Intentionally NOT listed in ``__all__`` — it is a module-level constant
#: that is part of the private implementation detail, not the public API.
SKU_PREFIX = "WH"


def format_sku(prefix: str, number):
    """Format a SKU string from a prefix and a sequential number.

    Args:
        prefix: The short alphabetic prefix identifying the product category.
        number: The sequential number to pad and append.

    Returns:
        A zero-padded SKU string such as ``"WH00042"``.
    """
    return f"{prefix}{number:05d}"


def load_csv(path) -> list[Product]:
    """Load product records from a CSV file and return a list of Products.

    The CSV must contain a header row with at least the columns ``sku``,
    ``name``, ``price``, and optionally ``quantity``.

    Args:
        path: Filesystem path to the CSV file.

    Returns:
        A list of :class:`~warehouse.models.Product` instances, one per row.

    Raises:
        FileNotFoundError: If *path* does not exist.
        KeyError: If a required column is absent from the CSV header.
    """
    products: list[Product] = []
    with Path(path).open(newline="", encoding="utf-8") as fh:
        reader = csv.DictReader(fh)
        for row in reader:
            products.append(Product.from_dict(row))
    return products
